# Check `docs/pipeline.md` to get info about this file

resources:
- name: hellonode-repository
  type: git
  source:
    uri: https://github.com/valshatravenko/hellonode.git
    branch: master

- name: hellonode-image
  type: docker-image
  source:
    repository: valshatravenko/hellonode
    username: {{docker_username}}
    password: {{docker_password}}

jobs:
- name: hellonode
  serial: true
  plan:
  - get: hellonode-repository
    trigger: true
  - put: hellonode-image
    params:
      build: hellonode-repository
